VPATH=../src/main
#CXXFLAGS?=-std=c++23 -Wall -Og -g -D_GLIBCXX_DEBUG
CXXFLAGS?=-std=c++23 -Wall -Og -g -fsanitize=address
#CXXFLAGS?=-std=c++23 -Wall -O3
LDFLAGS=-lgmpxx -lgmp -L/opt/homebrew/lib

clean:
	rm -rf build/*
