VPATH=../src/main
#CXXFLAGS?=-Og -g -D_GLIBCXX_DEBUG
#CXXFLAGS?=-Og -g -fsanitize=address
CXXFLAGS?=-O3

CXXFLAGS+=-std=c++23 -Wall -I/opt/homebrew/include
LDFLAGS=-lgmpxx -lgmp -L/opt/homebrew/lib

clean:
	rm -rf build
