#!/bin/sh
if [ "$1" = "--asan" ]; then
  KIND=.asan
  export CXXFLAGS="-Og -g -fsanitize=address"
  shift
  rm -f build/cpp/$1/main
elif [ "$1" = "--debug" ]; then
  KIND=.debug
  export CXXFLAGS="-g -D_GLIBCXX_DEBUG"
  shift
  rm -f build/cpp/$1/main
fi

p=${1:-<id>}
if [ -z "$1" ]; then
  echo "usage: ./run [--asan|--debug] <id>"
  echo "$cmd"
  exit 1
fi
input=$2
if [ -z "$input" ]; then
  input="input.txt"
fi
d="input/$1"
if [ ! -d "$d" ]; then
  d="input/`echo $1 | sed 's/\([0-9]*\).*/\1/'`"
fi
if [ -f "src/main/cpp/$1/main.cpp" ]; then
  echo "C++ version:"
  mkdir -p build/cpp/$1 >/dev/null
  make -C build -f ../Makefile cpp/$1/main >/dev/null &&
  time build/cpp/$1/main < $d/$input
  if [ -n "$KIND" ]; then
    mv build/cpp/$1/main{,$KIND}
  fi
fi
if [ -f "src/main/kotlin/hu/desnull/aoc2024/p$1/Main.kt" ]; then
  echo "Kotlin verion:"
  time gradle --console=plain -q -PmainClassName=hu.desnull.aoc2024.p$p.MainKt run < $d/$input
fi
