#!/bin/sh
p=${1:-<id>}
cmd="gradle --console=plain -q -PmainClassName=hu.desnull.aoc2021.p${p}.MainKt run"
if [ -z "$1" ]; then
  echo "usage: ./run <id>"
  echo "${cmd}"
  exit 1
fi
input=$2
if [ -z "$input" ]; then
  input="input.txt"
fi
if [ ! -z "$RUN_CPP" ]; then
  echo "C++ version:"
  (cd ../aoc-cpp/${1} && make main >/dev/null)
  cat ../input/${1}/${input} | ../aoc-cpp/${1}/main
fi
echo "Kotlin verion:"
cat ../input/${1}/${input} | ${cmd}
